Repository ARM-DOE/pyart, pull requests merged in 2022-04, with the labels that each got.

#1096 INSTALL: Use Setuptools For Installation
  .github/workflows/ci.yml
  .gitignore
  MANIFEST.in
  continuous_integration/environment-ci.yml
  doc/environment.yml
  pyart/__check_build/_check_build.c
  pyart/__init__.py
  pyart/_version.py
  pyart/correct/__init__.pxd
  pyart/correct/_fast_edge_finder.c
  pyart/correct/_fourdd_interface.c
  pyart/correct/_fourdd_interface.pyx
  pyart/correct/_unwrap_1d.c
  pyart/correct/_unwrap_2d.c
  pyart/correct/_unwrap_3d.c
  pyart/io/__init__.pxd
  pyart/io/_rsl_interface.c
  pyart/io/_rsl_interface.pxd
  pyart/io/_rsl_interface.pyx
  pyart/io/_sigmetfile.c
  pyart/io/nexrad_interpolate.c
  pyart/map/_gate_to_grid_map.c
  pyart/map/_load_nn_field_data.c
  pyart/map/ckdtree.c
  pyart/retrieve/_kdp_proc.c
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
  versioneer.py
Labels: Install, Large Scale, High Priority

#1099 MNT: Adding pytz as optional dependency.
  pyart/aux_io/rxm25.py
Labels: Enhancement, component: pyart.aux_io, Easy Fix

#1115 ENH: Use fsspec for io in pyart.io.common to read both local and remote files
  continuous_integration/environment-ci.yml
  pyart/io/common.py
  requirements.txt
Labels: Enhancement, component: pyart.io

#1116 FIX: Fix IO for NEXRAD Level 3 instantaneous precipitation rate (DPR)
  pyart/default_config.py
  pyart/io/nexrad_level3.py
Labels: Enhancement, component: pyart.io

#1118 ENH: Add a pypi release action
  .github/workflows/pypi-release.yml
Labels: Enhancement

#1136 ENH: Remove versioneer and add scm
  .gitattributes
  .github/workflows/build_docs.yml
  .github/workflows/ci.yml
  .github/workflows/pypi-release.yml
  pyart/__init__.py
  pyart/_version.py
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
  versioneer.py
Labels: Enhancement, Install

#1139 FIX: Use many linux build
  .github/workflows/pypi-release.yml
Labels: Install, Bug
